{"parentLocId":0, "parentMechId":0, "type":"Site", "display":"MSFC", "item":"Location", "id":"a"},
{"parentLocId":"a", "parentMechId":0, "type":"Building", "display":"4250", "item":"Location", "id":"b"},
{"parentLocId":"b", "parentMechId":0, "type":"Floor", "display":"Floor 1", "item":"Location", "id":"c"},
{"parentLocId":"c", "parentMechId":0, "type":"Room", "display":"38", "item":"Location", "id":"d"},
{"parentLocId":"d", "parentMechId":"bb", "type":"Equipment", "display":"VAV (1101)", "item":"Mechanical", "id":"e", "systemTags":{"groups":[],"props":["VAV"],"qualifiers":["Equipment"]}},
{"parentLocId":"d", "parentMechId":"e", "type":"End Point", "display":"SPT", "item":"Mechanical", "id":"f", "systemTags":{"groups":["Space"],"props":["Temperature"],"qualifiers":["Air","Sensor"]}},
{"parentLocId":"d", "parentMechId":"e", "type":"End Point", "display":"Space Humidity", "item":"Mechanical", "id":"g", "systemTags":{"groups":["Space"],"props":["Humidity"],"qualifiers":["Air","Sensor"]}},
{"parentLocId":"d", "parentMechId":"e", "type":"End Point", "display":"Space CO2", "item":"Mechanical", "id":"h",  "systemTags":{"groups":["Space"],"props":["CO2"],"qualifiers":["Air","Sensor"]}},
{"parentLocId":"d", "parentMechId":"e", "type":"End Point", "display":"Space Lights", "item":"Mechanical", "id":"i", "systemTags":{"groups":["Space"],"props":["Lights"],"qualifiers":["Control"]}},
{"parentLocId":"d", "parentMechId":"e", "type":"End Point", "display":"SAT", "item":"Mechanical", "id":"j", "systemTags":{"groups":["Supply Air"],"props":["Temperature"],"qualifiers":["Sensor"]}},
{"parentLocId":"d", "parentMechId":"e", "type":"End Point", "display":"SAFlow", "item":"Mechanical", "id":"k", "systemTags":{"groups":["Supply Air"],"props":["Flow"],"qualifiers":["Sensor"]}},
{"parentLocId":"d", "parentMechId":"e", "type":"Equipment", "display":"Fan (1101-F1)", "item":"Mechanical", "id":"l", "systemTags":{"groups":[],"props":["Fan"],"qualifiers":["Equipment"]}},
{"parentLocId":"d", "parentMechId":"l", "type":"End Point", "display":"Fan Status", "item":"Mechanical", "id":"m", "systemTags":{"groups":[],"props":["Status"],"qualifiers":["Sensor"]}},
{"parentLocId":"d", "parentMechId":"l", "type":"End Point", "display":"Fan Control", "item":"Mechanical", "id":"n", "systemTags":{"groups":[],"props":["Command"],"qualifiers":["Control"]}},
{"parentLocId":"b", "parentMechId":0, "type":"Floor", "display":"Floor 2", "item":"Location", "id":"aa"},
{"parentLocId":"aa", "parentMechId":0, "type":"Room", "display":"Room 201", "item":"Location", "id":"ab"},
{"parentLocId":"aa", "parentMechId":0, "type":"Equipment", "display":"VAV (2102)", "item":"Mechanical", "id":"ac",  "systemTags":{"groups":[],"props":["VAV"],"qualifiers":["Equipment"]}},
{"parentLocId":"ab", "parentMechId":"ac", "type":"End Point", "display":"Temperature", "item":"Mechanical", "id":"ad", "systemTags":{"groups":["Space"],"props":["Temperature"],"qualifiers":["Air","Sensor"]}},
{"parentLocId":"aa", "parentMechId":"ac", "type":"End Point", "display":"Humidity", "item":"Mechanical", "id":"ae", "systemTags":{"groups":["Space"],"props":["Humidity"],"qualifiers":["Air","Sensor"]}},
{"parentLocId":"aa", "parentMechId":"ac", "type":"End Point", "display":"CO2", "item":"Mechanical", "id":"af", "systemTags":{"groups":["Space"],"props":["CO2"],"qualifiers":["Air","Sensor"]}},
{"parentLocId":"aa", "parentMechId":"ac", "type":"End Point", "display":"Lights", "item":"Mechanical", "id":"ag", "systemTags":{"groups":["Space"],"props":["Lights"],"qualifiers":["Control"]}},
{"parentLocId":"aa", "parentMechId":"ac", "type":"End Point", "display":"Temperature", "item":"Mechanical", "id":"ah",  "systemTags":{"Supply Air":["Space"],"props":["Temperature"],"qualifiers":["Sensor"]}},
{"parentLocId":"aa", "parentMechId":"ac", "type":"End Point", "display":"Flow", "item":"Mechanical", "id":"ai", , "systemTags":{"groups":["Supply Air"],"props":["Flow"],"qualifiers":["Sensor"]}},
{"parentLocId":"aa", "parentMechId":"ac", "type":"Equipment", "display":"Fan (2102-F1)", "item":"Mechanical", "id":"aj", "systemTags":{"groups":[],"props":["Fan"],"qualifiers":["Equipment"]}},
{"parentLocId":"aa", "parentMechId":"aj", "type":"End Point", "display":"Status", "item":"Mechanical", "id":"ak", "systemTags":{"groups":[],"props":["Status"],"qualifiers":["Sensor"]}},
{"parentLocId":"aa", "parentMechId":"aj", "type":"End Point", "display":"Control", "item":"Mechanical", "id":"al", "systemTags":{"groups":[],"props":["Command"],"qualifiers":["Control"]}},
{"parentLocId":"b", "parentMechId":0, "type":"Floor", "display":"Penthouse", "item":"Location", "id":"ba"},
{"parentLocId":"ba", "parentMechId":0, "type":"Equipment", "display":"AHU (1)", "item":"Mechanical", "id":"bb", "systemTags":{"groups":[],"props":["AHU"],"qualifiers":["Equipment"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Supply Air Temperature", "item":"Mechanical", "id":"bb", "systemTags":{"groups":["Supply Air"],"props":["Temperature"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Supply Air High Static Alarm", "item":"Mechanical", "id":"bc", "systemTags":{"groups":["Supply Air"],"props":["High Static"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Supply Air Static Pressure", "item":"Mechanical", "id":"bd", "systemTags":{"groups":["Supply Air"],"props":["Static Pressure"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Supply Air Humidity", "item":"Mechanical", "id":"be", "systemTags":{"groups":["Supply Air"],"props":["Humidity"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Supply Air Humidifier (1-H1)", "item":"Mechanical", "id":"bf", "systemTags":{"groups":["Supply Air"],"props":["Humidifer"],"qualifiers":["Equipment"]}},
{"parentLocId":"ba", "parentMechId":"bf", "type":"End Point", "display":"Humidifier Enable", "item":"Mechanical", "id":"bg", "systemTags":{"groups":[],"props":["Enable"],"qualifiers":["Control"]}},
{"parentLocId":"ba", "parentMechId":"bf", "type":"End Point", "display":"Humidifier Control", "item":"Mechanical", "id":"bh", "systemTags":{"groups":[],"props":["Control"],"qualifiers":["Control"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Return Air Temperature", "item":"Mechanical", "id":"bi", "systemTags":{"groups":["Return Air"],"props":["Temperature"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Return Air Static Pressure", "item":"Mechanical", "id":"bj", "systemTags":{"groups":["Return Air"],"props":["Static Pressure"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Return Air Humidity", "item":"Mechanical", "id":"bk", "systemTags":{"groups":["Return Air"],"props":["Humidity"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Return Air CO2", "item":"Mechanical", "id":"bl", "systemTags":{"groups":["Return Air"],"props":["CO2"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Return Air Flow", "item":"Mechanical", "id":"bm", "systemTags":{"groups":["Return Air"],"props":["Flow"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"Equipment", "display":"Return Air Damper (1-D1)", "item":"Mechanical", "id":"bn", "systemTags":{"groups":["Return Air"],"props":["Damper"],"qualifiers":["Equipment"]}},
{"parentLocId":"ba", "parentMechId":"bn", "type":"End Point", "display":"Damper Status", "item":"Mechanical", "id":"bo", "systemTags":{"groups":[],"props":["Status"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bn", "type":"End Point", "display":"Damper Control", "item":"Mechanical", "id":"bp", "systemTags":{"groups":[],"props":["Control"],"qualifiers":["Control"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Mixed Air Temperature", "item":"Mechanical", "id":"bq", "systemTags":{"groups":["Mixed Air"],"props":["Temperature"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Mixed Air Freeze Low Limit Alarm", "item":"Mechanical", "id":"br", "systemTags":{"groups":["Mixed Air"],"props":["Freeze Low Limit"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Mixed Air Filter Pressure", "item":"Mechanical", "id":"bs", "systemTags":{"groups":["Mixed Air"],"props":["Filter Pressure"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Outside Air Temperature", "item":"Mechanical", "id":"bt", "systemTags":{"groups":["Outside Air"],"props":["Temperature"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Outside Air CO2", "item":"Mechanical", "id":"bu", "systemTags":{"groups":["Outside Air"],"props":["CO2"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Outside Air Static Pressure", "item":"Mechanical", "id":"bv", "systemTags":{"groups":["Outside Air"],"props":["Static Pressure"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Outside Air Humidity", "item":"Mechanical", "id":"bw", "systemTags":{"groups":["Outside Air"],"props":["Humidity"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"End Point", "display":"Outside Air Flow", "item":"Mechanical", "id":"bx", "systemTags":{"groups":["Outside Air"],"props":["Flow"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"bb", "type":"Equipment", "display":"Outside Air Damper (1-D1)", "item":"Mechanical", "id":"by", "systemTags":{"groups":["Outside Air"],"props":["Damper"],"qualifiers":["Equipment"]}},
{"parentLocId":"ba", "parentMechId":"by", "type":"End Point", "display":"Damper Status", "item":"Mechanical", "id":"bz", "systemTags":{"groups":[],"props":["Status"],"qualifiers":["Sensor"]}},
{"parentLocId":"ba", "parentMechId":"by", "type":"End Point", "display":"Damper Control", "item":"Mechanical", "id":"bba", "systemTags":{"groups":[],"props":["Control"],"qualifiers":["Control"]}}